# Generated by Django 2.2.12 on 2020-05-02 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Salle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=256, verbose_name='Nom de la salle')),
            ],
        ),
        migrations.CreateModel(
            name='Mot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mot', models.CharField(max_length=256, verbose_name='Mot')),
                ('libre', models.BooleanField(default=True, verbose_name='Est-ce que le mot est libre?')),
                ('passed', models.BooleanField(default=False, verbose_name='Est passed?')),
                ('guessed', models.BooleanField(default=False, verbose_name='Est passed?')),
                ('tour', models.BooleanField(default=False, verbose_name='Currently in tour')),
                ('salle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chapeau.Salle')),
            ],
        ),
        migrations.CreateModel(
            name='Jouer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=256, verbose_name='Nom de le jouer')),
                ('hatter', models.BooleanField(default=False, verbose_name='Etat de  le jouer')),
                ('score', models.IntegerField(default=0)),
                ('salle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chapeau.Salle')),
            ],
        ),
    ]
